# Version: 0.0.1
FROM r-base 
MAINTAINER Zebulun Arendsee "zbwrnz@gmail.com"
RUN apt-get update
RUN apt-get install -y git
CMD ["/usr/bash"]
EXPOSE 80

# to build:
# $ sudo docker build -t="arendsee/test:v0.0.1" .
